### PR TITLE
Add simple CI based on GitHub Actions (fixes #88)

### LINKED ISSUE #88: CI present but inactive?
Hi!

I found a file [`.travis.yml`](https://github.com/tibirna/qgit/blob/master/.travis.yml) in this repository but recent commits are missing checkmarks/crosses so it seems that Travis CI has been deactivated? What is the status and the story of CI with QGit — does it need help? Does it need a replacement using GitHub Actions? I might be able to help but I'd need to be sure what is needed.
PS: I saw #65 but I'm not sure that's the right direction.

Best, Sebastian

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #88

I'm happy to do adjusts as needed

Please see [this run](https://github.com/hartwork/qgit/runs/495215057?check_suite_focus=true) in my fork for — once merged — what the result is going to look like, exactly:
https://github.com/hartwork/qgit/runs/495215057?check_suite_focus=true

### CODE REVIEW

**Comment by hartwork** [comment]
@tibirna what do you think?

**Comment by hartwork** [comment]
@tibirna any thoughts?

**Comment by hartwork** [comment]
@tibirna any thoughts?

**Comment by tibirna** [comment]
I apologize for my low reactivity on this. I merged the request. Thanks.

**Comment by hartwork** [comment]
That is great news, thank you! :tada:

**Pull request merged**
