### PR TITLE
Upgrade icons

### PR DESCRIPTION
**Pull request by filiperinaldi**
Upgrade replacing the current low resolution PNG files with modern,
vector based icons from KDE's Breeze project (v5.49.0)

These offer better GUI, specially on high definition displays.

As part of these patch, new file format icons have been added.

### CODE REVIEW

**Comment by filiperinaldi** [comment]
Here is a preview showing also the new file format icons added:

image

**Comment by filiperinaldi** [comment]
There seems to be a problem with cmake install (missing the qgit.png) which was replaced by git-gui.svg. I will update the PR to fix it.

Also, one can see my patch and @mwoehlke's #13 PR choose slightly different icons. Would be nice to get my PR and @mwoehlke's PR aligned on the icon's choice. On a Breeze based OS, my patch and @mwoehlke's patch should result on exactly the same UI. I will review the ones I picked.

**Comment by tibirna** [comment]
Thank you very much for this work.
Two issues:
- some of the icon choices can lead to confusion. E.g. the icons picked for the "Open" and "Refresh view" toolbar buttons are almost identical
- the qgit icon should not change appearance. It is one of the main branding means of the application. It would be nice to get it converted to SVG, but otherwise it should look exactly the same as now.

Thanks

**Comment by tibirna** [comment]
Hello Filipe
I merged mwoelhke's PR #56 thinking that this should simplify your intention to review your icon choices. I hope it will not create unwarranted amounts of time expense. I guess you will want to rebase your upgrade_icons branch on top of the new master. When you will add the new icons, I will tag the 2.9 release.

Thanks for your understanding.

**Comment by mwoehlke** [comment]
> the icons picked for the "Open" and "Refresh view" toolbar buttons are almost identical

Hmm, yeah... I don't think `folder-sync` is the right icon for that. The old icon was `view-refresh`. (#56 used `folder-sync` for "Check working directory".)

**Comment by filiperinaldi** [comment]
Hi, yes, I agree view-refresh is a better option. I changed this and a few other last evening but I haven't finished going through @mwoehlke's PR version yet.

**Comment by filiperinaldi** [comment]
Hi, I updated the patch.

**Comment by tibirna** [comment]
Thanks for this! I restored the corrupted `src/resources/qgit.png` and merged into master. I will tag the 2.10 version soon.

Thanks again and a Happy New Year!

**Pull request merged**
