### PR TITLE
Fix version string for 2.10

### PR DESCRIPTION
**Pull request by hartwork**

### CODE REVIEW

**Comment by tibirna** [comment]
Thank you for your careful eye and for fixing this. I forget to complete this step, sometimes.

**Comment by hartwork** [comment]
@a17r should I cherry-pick this^^ patch to the packaging in Gentoo?

**Comment by tibirna** [comment]
@hartwork and @a17r, please note that I re-tagged the qgit-2.10 version so that Sebastian's version correction is included. I apologise for the inconvenience.

**Comment by hartwork** [comment]
@tibirna that is good to know and has some benefits. I should note that it does violate good practice rule "never re-release under the same name" and rule "never move a Git tag" though. So thanks but let's do a new second tag like "2.10.1" instead for the next situation like that, please. Okay?

**Comment by hartwork** [comment]
PS: @tibirna here is proof why re-tagging is a problem in practice. Distros store filesize and checksum metadata of the upstream tarball and re-tagging changes the checksum and then the build breaks for everyone that builds without a mirror holding a copy of the old file. Here's what you'd see in Gentoo:

```console
# rm /usr/portage/distfiles/qgit-2.10.tar.gz 

# GENTOO_MIRRORS= ebuild qgit-2.10.ebuild clean unpack
Appending /home/sping/__playground/gentoo-GIT to PORTDIR_OVERLAY...
>>> Downloading 'https://github.com/tibirna/qgit/archive/qgit-2.10.tar.gz'
--2022-01-11 18:18:07--  https://github.com/tibirna/qgit/archive/qgit-2.10.tar.gz
Resolving github.com... 140.82.121.3
Connecting to github.com|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/tibirna/qgit/tar.gz/qgit-2.10 [following]
--2022-01-11 18:18:08--  https://codeload.github.com/tibirna/qgit/tar.gz/qgit-2.10
Resolving codeload.github.com... 140.82.121.9
Connecting to codeload.github.com|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/usr/portage/distfiles/qgit-2.10.tar.gz.__download__’

/usr/portage/distfiles/qgit-2.10.tar.gz.__downl     [ <=>                                                                                                 ] 216.87K  --.-KB/s    in 0.08s   

2022-01-11 18:18:09 (2.61 MB/s) - ‘/usr/portage/distfiles/qgit-2.10.tar.gz.__download__’ saved [222077]

!!! Fetched file: qgit-2.10.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      222077
!!! Expected: 222085
Refetching... File renamed to '/usr/portage/distfiles/qgit-2.10.tar.gz._checksum_failure_.qg0j37fa'

!!! Couldn't download 'qgit-2.10.tar.gz'. Aborting.
```

I'm sharing that to prove that it's not just q theoretical issue. @a17r I'll go fix the Manifest in Gentoo now.

**Comment by tibirna** [comment]
Thank you for the information. I usually avoid doing these kinds of manipulations, but I still did it this time because I assumed the tag move was done soon enough after the initial tagging that it wouldn't matter. I was not aware of the gentoo practice.

**Comment by hartwork** [comment]
@tibirna it's not super specific to Gentoo (if I made it sound like that): It affects everyone who stores the download URL rather than a copy of the tarball. There is one other distro named "KaOSx" that is affected in practice today. I have notified them through a bug report at https://github.com/KaOSx/apps/issues/206 now. The only other distro that has something called 2.10 by now is LiGurOS and they get QGit from Gentoo, to my understanding, so they'll likely fix automatically. That all info I have from https://repology.org/project/qgit/versions . I love repology :smiley: 

@a17r @tibirna I have fixed the Gentoo package now at https://github.com/gentoo/gentoo/commit/82f61656e59454131d94c763c2118f7d316e38a5 .

**Pull request merged**
